### ISSUE TITLE
slug not working

### ISSUE THREAD

**Issue by bhdrnzl** [epigra/tr-geozones#20]
How can I use slugs when seeding files? I also created country, city and district models for geozone.

**Comment by jnbn** [comment]
@bhdrnzl merhaba, seeder'ları mı kullanıyorsun yoksa CityImport commandı üzerinden mi slug kullanmak istiyorsun? Şayet seeder kullanıyorsan;  direkt olarak DB transaction olarak veritabanına eklendiği için ilk aşamada slug eklemek mümkün olmayacaktır.

seed ettikten ve modeline sluggable gibi bir eklenti kurtuktan sonra tüm modellerin üzerinden geçip gerekli şekilde düzenleyen bir comment yazabilirsin.

Seeder yerine excel importer kullanmayı tercih ediyorsan sluggable olan modellerinde Model boot'unda slug belirleyen herhangi bir paket veya özellik kullanıyorsan, otomatik olarak doğru sluglar ile oluşacaktır

**Comment by bhdrnzl** [comment]
teşekkürler..
