### ISSUE TITLE
Something is off...

### ISSUE THREAD

**Issue by briggsm** [epigra/tr-geozones#22]
Merhabalar,

Bugun ilk defa kullanmaya calisiyordum...  

composer require epigra/trgeozones yaptim, migrate yaptim, ve db:seed yaptim. Hersey iyi gecti. Ama veritabani kontrol ettiginde, sey fark ettim:

geozone_counties table'da: Kadıköy (id: 494) (city_id: 41)  - city 41 is Kocaeli, ama Kadikoy, Istanbul'da. Ve butun Istanbul'daki "counties" 41 city'de (Kocaeli).

**Comment by Biostate** [comment]
Merhabalar, Seeder'ları güncelledim. Paketinizi lütfen 4.2 versiyonuna çıkarınız.

**Comment by enespolat24** [comment]
closed due to inactivity
