### ISSUE TITLE
GeozoneCityDistrictsTableSeeder

### ISSUE THREAD

**Issue by jacklondon** [epigra/tr-geozones#3]
Merhaba 
GeozoneCityDistrictsTableSeeder classını çalıştırmak istediğimde terminal hiç bir işlem yapmadan komut satırına dönüyor. Bu arada sayfayı php storm üzerinde açmak istediğimde maksimum 40000 satır gösteriyor. halbuki class 600 küsür bin satır. nasıl yükleyebilirim mahalleleri?

**Comment by jnbn** [comment]
Selam,

PHPStorm, VSCode gibi editörlerde syntax highlighting vs gibi durumlardan dolayı dosyanın açılamaması mümkün. 

Diğer kısımda kodun içerisinde problem olmaması için php ini memory ayarlarını bypass eden satırlar vardı fakat loglara bakmak lazım.

Problem yaşanan bir durumsa sql dumpları koyabiliriz

**Comment by jnbn** [comment]
http://epigra.com/packages/tr_geozones_sql_dump.zip adresinden dumpları indirebilirsiniz.
