### ISSUE TITLE
[oneri] Migrationlarin publish edilebilmesi

### ISSUE THREAD

**Issue by erdemkeren** [epigra/tr-geozones#6]
Paketi kurduktan sonra `php artisan vendor:publish` diyerek migration ve seederlarin vendordan client uygulama kaynagina kopyalanmasi guzel olabilir.

**Comment by taliptako** [comment]
Evet bu güzel olur migration larda index eklememiz gerekebilir

**Comment by jnbn** [comment]
3.0'ı publishable migration olacak şekilde çıkıyorum. 

Migration isimleri değiştirildiği için eski migrationları tekrar migrate etmeye çalışabilir; bu durumda gerekli batch id ile mevcut migration isimlerini migrations tablosuna eklemeniz (eski projelerde, bir defaya mahsus) sanırım yeterli olacaktır.
