### ISSUE TITLE
[oneri] Migration isimleri ve dosya isimlerinin tutarliliginin iyilestirilmesi

### ISSUE THREAD

**Issue by erdemkeren** [epigra/tr-geozones#7]
Merhaba,

Paketin calismasina engel olmasa da,

`create_cities_table` migration'inin `create_geozone_cities_table` olarak...*

ya da var olan tablo isminin

`geozone_cities` yerine `cities` olarak duzenlenmesi ile...*

migration ismi ve yaptigi is daha tutarli hale gelebilir.

*: Diger model, table ve migration isimleri de ayni sekilde.

Eg:

```php
migration: create_cities_table
table: cities
model: city
```

**Comment by erdemkeren** [comment]
Simdi fark ettim ki zaten bu sekilde baslanip sonradan degistirilmis zira down metodlarinda `geo_cities` degil `cities` yaziyor ve hata veriyor.

**Comment by jnbn** [comment]
Selam Erdem,

Bir sonraki versiyon için model isimleri olmasada migration isimlerini düzeltecek bir update çıkacağım ve 3.0 olarak tagleyeceğim.
